on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:

name: Render indicator handbook

jobs:

  build_deploy:
    runs-on: ubuntu-latest
    if: github.repository	== 'PathOS-project/indicator_handbook'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render quarto project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Install pagemerger
        run: |
          curl -OL https://github.com/tymbaca/pagemerger/releases/download/v1.0.0/pagemerger_1.0-1_amd64.deb
          sudo dpkg -i pagemerger_1.0-1_amd64.deb
          sudo apt-get install -y aspnetcore-runtime-7.0
          sudo chmod 755 /usr/local/bin/pagemerger

      - name: Merge cover page with rendered docx
        run: |
          pagemerger out.docx etc/cover.docx _book/Open-Science-Indicator-Handbook.docx
          mv out.docx _book/Open-Science-Indicator-Handbook.docx

      - name: Install SSH key
        if: github.ref == 'refs/heads/main'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.WEBSITE_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.WEBSITE_KNOWN_HOST }}
          config: ${{ secrets.WEBSITE_SSH_CONFIG }}
          if_key_exists: fail

      - name: Deploy using rsync
        if: github.ref == 'refs/heads/main'
        run: |
          ls -R
          rsync -avz --delete --filter='P .htaccess' _book/ website:domains/pathos.traag.net/public_html/
